name: Build Windows

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build-windows-2019:
    runs-on: windows-2019
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.2'
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          mkdir build
          cmake -D CMAKE_CXX_FLAGS="/bigobj" -B build .
          cmake --build build --parallel $(nproc)
