name: Build Ubuntu

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:


jobs:
  build-ubuntu-22:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.2'
      - name: Install dependencies
        run: |
          sudo apt --yes install uuid-dev
      - name: Checkout
        uses: actions/checkout@v4
      - name: Environment variables
        run: |
          echo "BUILD_DIR=$(mktemp --directory)" >> "$GITHUB_ENV"
      - name: Build
        run: |
          cmake -B "$BUILD_DIR" .
          cmake --build "$BUILD_DIR" --parallel $(nproc)
