name: Release Skydel example plugins

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag'
        required: true
        type: string
        default: 'vXX.YY.ZZ'

env:
  ARTIFACT_UBUNTU: skydel-example-plugins-ubuntu
  ARTIFACT_WINDOWS: skydel-example-plugins-windows

jobs:
  build-ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.2'
      - name: Install dependencies
        run: |
          sudo apt --yes install uuid-dev
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          cmake -D PLUGIN_INSTALL_DIR="${{ runner.temp }}/${{ env.ARTIFACT_UBUNTU }}" -B "${{ runner.temp }}/build" .
          cmake --build "${{ runner.temp }}/build" --parallel $(nproc)
          cmake --install "${{ runner.temp }}/build"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_UBUNTU }}
          path: ${{ runner.temp }}/${{ env.ARTIFACT_UBUNTU }}
          retention-days: 1
          overwrite: true


  release:
    needs: [build-ubuntu]
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/artifacts
      - name: Archive artifacts
        run: |
          cd "${{ runner.temp }}/artifacts"
          find . -mindepth 1 -maxdepth 1 -type d -exec zip -r "{}.zip" "{}" \;
      - name: GitHub release
        run: |
          find "${{ runner.temp }}/artifacts" -mindepth 1 -maxdepth 1 -type f -exec gh release create "${{ inputs.release_tag }}" --generate-notes "{}" +
