name: Release Skydel example plugins

on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Release name'
        required: true
        type: string
        default: 'Skydel example plugins vXX.YY.ZZ'

env:
  ARTIFACT_UBUNTU_22: skydel-plugins-ubuntu-22


jobs:
  build-ubuntu-22:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.2'
      - name: Install dependencies
        run: |
          sudo apt --yes install uuid-dev
      - name: Checkout
        uses: actions/checkout@v4
      - name: Environment variables
        run: |
          echo "BUILD_DIR=$(mktemp --directory)" >> "$GITHUB_ENV"
          echo "INSTALL_DIR=$(realpath ${{ env.ARTIFACT_UBUNTU_22 }})" >> "$GITHUB_ENV"
      - name: Build
        run: |
          cmake -D PLUGIN_INSTALL_DIR="$INSTALL_DIR" -B "$BUILD_DIR" .
          cmake --build "$BUILD_DIR" --parallel $(nproc)
          cmake --install "$BUILD_DIR"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_UBUNTU_22 }}
          path: ${{ env.ARTIFACT_UBUNTU_22 }}
          retention-days: 1
          overwrite: true


  release:
    needs: [build-ubuntu-22]
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download all artifacts
        uses: actions/download-artifact@v4
      - name: GitHub release
        run: |
          find . -name "skydel-plugins-ubuntu-*" -type d -mindepth 1 -maxdepth 1 -exec zip -r "{}.zip" "{}" \;
          find . -name "skydel-plugins-ubuntu-*" -type f -mindepth 1 -maxdepth 1 -exec gh release create "${{ inputs.release_name }}" --generate-notes "{}" +
