name: Release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag'
        required: true
        type: string
        default: 'vXX.YY.ZZ'

jobs:
  build-ubuntu:
    uses: ./.github/workflows/build_ubuntu.yml

  build-windows:
    uses: ./.github/workflows/build_windows.yml

  release:
    needs: [build-ubuntu, build-windows]
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set environment variables
        run: |
          echo "ARTIFACTS_PATH=${{ runner.temp }}/artifacts" >> "$GITHUB_ENV"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ env.ARTIFACTS_PATH }}
      - name: Archive artifacts
        run: |
          cd "${ARTIFACTS_PATH}"
          find . -mindepth 1 -maxdepth 1 -type d -exec zip -r "{}.zip" "{}" \;
      - name: Create GitHub release
        run: |
          find "${{ runner.temp }}/artifacts" -mindepth 1 -maxdepth 1 -type f -exec gh release create "${{ inputs.release_tag }}" --generate-notes "{}" +
